// demowithmcp/frontend/src/app/components/a2ui-renderer/a2ui-renderer.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CardWidgetComponent } from '../widgets/card-widget/card-widget.component';
import { AccountSummaryWidgetComponent } from '../widgets/account-summary-widget/account-summary-widget.component';
import { DepositWidgetComponent } from '../widgets/deposit-widget/deposit-widget.component';
import { WithdrawalWidgetComponent } from '../widgets/withdrawal-widget/withdrawal-widget.component';

@Component({
  selector: 'app-a2ui-renderer',
  standalone: true,
  imports: [
    CommonModule,
    CardWidgetComponent,
    AccountSummaryWidgetComponent,
    DepositWidgetComponent,
    WithdrawalWidgetComponent
  ],
  template: `
    <div class="a2ui-renderer">
      <app-card-widget 
        *ngIf="message?.type === 'card'" 
        [data]="message.data">
      </app-card-widget>
      <app-account-summary-widget 
        *ngIf="message?.type === 'account_summary'" 
        [data]="message.data">
      </app-account-summary-widget>
      <app-deposit-widget 
        *ngIf="message?.type === 'deposit'" 
        [data]="message.data">
      </app-deposit-widget>
      <app-withdrawal-widget 
        *ngIf="message?.type === 'withdrawal'" 
        [data]="message.data">
      </app-withdrawal-widget>
      <div *ngIf="!message || !message.type" class="a2ui-error">
        Invalid A2UI message format
      </div>
      <div *ngIf="message?.type && !isValidType(message.type)" class="a2ui-error">
        Unknown widget type: {{ message.type }}
      </div>
    </div>
  `,
  styles: [`
    .a2ui-renderer {
      width: 100%;
    }

    .a2ui-error {
      padding: 1rem;
      background: #fee;
      color: #c33;
      border-radius: 6px;
      border: 1px solid #fcc;
    }
  `]
})
export class A2UIRendererComponent {
  @Input() message: any;

  isValidType(type: string): boolean {
    return ['card', 'account_summary', 'deposit', 'withdrawal'].includes(type);
  }
}

// demowithmcp/frontend/src/components/A2UIRenderer.tsx
import React from 'react'
import CardWidget from './widgets/CardWidget'
import AccountSummaryWidget from './widgets/AccountSummaryWidget'
import DepositWidget from './widgets/DepositWidget'
import WithdrawalWidget from './widgets/WithdrawalWidget'
import './A2UIRenderer.css'

interface A2UIRendererProps {
  message: any
}

function A2UIRenderer({ message }: A2UIRendererProps) {
  if (!message || !message.type) {
    return <div className="a2ui-error">Invalid A2UI message format</div>
  }

  const validTypes = ['card', 'account_summary', 'deposit', 'withdrawal']
  if (!validTypes.includes(message.type)) {
    return <div className="a2ui-error">Unknown widget type: {message.type}</div>
  }

  return (
    <div className="a2ui-renderer">
      {message.type === 'card' && <CardWidget data={message.data} />}
      {message.type === 'account_summary' && <AccountSummaryWidget data={message.data} />}
      {message.type === 'deposit' && <DepositWidget data={message.data} />}
      {message.type === 'withdrawal' && <WithdrawalWidget data={message.data} />}
    </div>
  )
}

export default A2UIRenderer
