// A2UI-Demo/angular-client/src/app/components/widgets/card-widget/card-widget.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

/**
 * Card Widget Template
 * Displays information in a card format with title, content, and optional actions
 */
@Component({
  selector: 'app-card-widget',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './card-widget.component.html',
  styleUrls: ['./card-widget.component.css']
})
export class CardWidgetComponent {
  @Input() data: any;

  handleAction(action: any) {
    if (action.onClick) {
      action.onClick();
    } else {
      console.log('Action clicked:', action.label, action.data);
      alert(`Action: ${action.label}\nData: ${JSON.stringify(action.data || {}, null, 2)}`);
    }
  }
}


<div class="card-widget" *ngIf="data">
  <div class="card-image" *ngIf="data.image">
    <img [src]="data.image.url || data.image" [alt]="data.image.alt || data.title || 'Card image'" />
  </div>
  <div class="card-content">
    <h3 class="card-title" *ngIf="data.title">{{ data.title }}</h3>
    <div class="card-body" *ngIf="data.content">
      <p *ngIf="typeof data.content === 'string'">{{ data.content }}</p>
      <div *ngIf="typeof data.content !== 'string'">{{ data.content }}</div>
    </div>
    <div class="card-footer" *ngIf="data.footer">{{ data.footer }}</div>
  </div>
  <div class="card-actions" *ngIf="data.actions && data.actions.length > 0">
    <button
      *ngFor="let action of data.actions; let i = index"
      [class]="'card-action' + (action.primary ? ' primary' : '')"
      (click)="handleAction(action)"
    >
      {{ action.label }}
    </button>
  </div>
</div>
<div class="widget-error" *ngIf="!data">
  No data provided for card widget
</div>

// demowithmcp/frontend/src/components/widgets/CardWidget.tsx
import React from 'react'
import './CardWidget.css'

interface CardWidgetProps {
  data: any
}

function CardWidget({ data }: CardWidgetProps) {
  if (!data) return <div className="widget-error">No data provided for card widget</div>

  const handleAction = (action: any) => {
    if (action.data && action.data.action) {
      console.log('Action triggered:', action.data.action)
      alert(`Action: ${action.label}\nWould trigger: ${action.data.action}`)
    } else {
      console.log('Action clicked:', action.label, action.data)
      alert(`Action: ${action.label}`)
    }
  }

  return (
    <div className="card-widget">
      <div className="card-content">
        {data.title && <h3 className="card-title">{data.title}</h3>}
        {data.content && (
          <div className="card-body">
            <p dangerouslySetInnerHTML={{ __html: data.content.replace(/\n/g, '<br>') }} />
          </div>
        )}
        {data.footer && <div className="card-footer">{data.footer}</div>}
      </div>
      {data.actions && data.actions.length > 0 && (
        <div className="card-actions">
          {data.actions.map((action: any, index: number) => (
            <button
              key={index}
              className={`card-action ${action.primary ? 'primary' : ''}`}
              onClick={() => handleAction(action)}
            >
              {action.label}
            </button>
          ))}
        </div>
      )}
    </div>
  )
}

export default CardWidget
