// demowithmcp/frontend/src/app/components/widgets/deposit-widget/deposit-widget.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-deposit-widget',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './deposit-widget.component.html',
  styleUrls: ['./deposit-widget.component.css']
})
export class DepositWidgetComponent {
  @Input() data: any;
  formData: any = {};

  onSubmit() {
    console.log('Deposit form submitted:', this.formData);
    alert(`Deposit submitted!\nAmount: ${this.formData.amount}\nSource: ${this.formData.source}\nMemo: ${this.formData.memo || 'N/A'}`);
    // Reset form
    this.formData = {};
  }

  isFormValid(): boolean {
    if (!this.data?.fields) return false;
    
    const requiredFields = this.data.fields.filter((f: any) => f.required);
    return requiredFields.every((field: any) => {
      const value = this.formData[field.name];
      return value !== undefined && value !== null && value !== '';
    });
  }
}


<div class="deposit-widget" *ngIf="data">
  <div class="widget-header">
    <h3 class="widget-title">{{ data.title }}</h3>
    <p class="widget-description" *ngIf="data.description">{{ data.description }}</p>
  </div>

  <form (ngSubmit)="onSubmit()" class="deposit-form">
    <div *ngFor="let field of data.fields" class="form-field">
      <label [for]="field.name">
        {{ field.label }}
        <span *ngIf="field.required" class="required">*</span>
      </label>
      
      <input
        *ngIf="field.type === 'text' || field.type === 'number' || field.type === 'email'"
        [id]="field.name"
        [name]="field.name"
        [type]="field.type"
        [placeholder]="field.placeholder || ''"
        [required]="field.required"
        [min]="field.min"
        [max]="field.max"
        [step]="field.step"
        [(ngModel)]="formData[field.name]"
        class="form-input"
      />

      <select
        *ngIf="field.type === 'select'"
        [id]="field.name"
        [name]="field.name"
        [required]="field.required"
        [(ngModel)]="formData[field.name]"
        class="form-select"
      >
        <option value="" disabled>Select {{ field.label }}</option>
        <option *ngFor="let option of field.options" [value]="option.value">
          {{ option.label }}
        </option>
      </select>

      <textarea
        *ngIf="field.type === 'textarea'"
        [id]="field.name"
        [name]="field.name"
        [placeholder]="field.placeholder || ''"
        [required]="field.required"
        [rows]="field.rows || 4"
        [(ngModel)]="formData[field.name]"
        class="form-textarea"
      ></textarea>
    </div>

    <div class="form-actions">
      <button 
        type="submit" 
        class="submit-button"
        [disabled]="!isFormValid()"
      >
        {{ data.submitLabel || 'Submit' }}
      </button>
    </div>
  </form>
</div>

// demowithmcp/frontend/src/components/widgets/DepositWidget.tsx
import React, { useState } from 'react'
import './DepositWidget.css'

interface DepositWidgetProps {
  data: any
}

function DepositWidget({ data }: DepositWidgetProps) {
  const [formData, setFormData] = useState<any>({})

  if (!data) return <div className="widget-error">No data provided for deposit widget</div>

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    console.log('Deposit form submitted:', formData)
    alert(
      `Deposit submitted!\nAmount: ${formData.amount}\nSource: ${formData.source}\nMemo: ${formData.memo || 'N/A'}`
    )
    setFormData({})
  }

  const isFormValid = (): boolean => {
    if (!data?.fields) return false

    const requiredFields = data.fields.filter((f: any) => f.required)
    return requiredFields.every((field: any) => {
      const value = formData[field.name]
      return value !== undefined && value !== null && value !== ''
    })
  }

  const handleFieldChange = (name: string, value: any) => {
    setFormData((prev: any) => ({
      ...prev,
      [name]: value
    }))
  }

  return (
    <div className="deposit-widget">
      <div className="widget-header">
        <h3 className="widget-title">{data.title}</h3>
        {data.description && <p className="widget-description">{data.description}</p>}
      </div>

      <form onSubmit={handleSubmit} className="deposit-form">
        {data.fields?.map((field: any, index: number) => (
          <div key={index} className="form-field">
            <label htmlFor={field.name}>
              {field.label}
              {field.required && <span className="required">*</span>}
            </label>

            {(field.type === 'text' || field.type === 'number' || field.type === 'email') && (
              <input
                id={field.name}
                name={field.name}
                type={field.type}
                placeholder={field.placeholder || ''}
                required={field.required}
                min={field.min}
                max={field.max}
                step={field.step}
                value={formData[field.name] || ''}
                onChange={(e) => handleFieldChange(field.name, e.target.value)}
                className="form-input"
              />
            )}

            {field.type === 'select' && (
              <select
                id={field.name}
                name={field.name}
                required={field.required}
                value={formData[field.name] || ''}
                onChange={(e) => handleFieldChange(field.name, e.target.value)}
                className="form-select"
              >
                <option value="" disabled>
                  Select {field.label}
                </option>
                {field.options?.map((option: any, optIndex: number) => (
                  <option key={optIndex} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </select>
            )}

            {field.type === 'textarea' && (
              <textarea
                id={field.name}
                name={field.name}
                placeholder={field.placeholder || ''}
                required={field.required}
                rows={field.rows || 4}
                value={formData[field.name] || ''}
                onChange={(e) => handleFieldChange(field.name, e.target.value)}
                className="form-textarea"
              />
            )}
          </div>
        ))}

        <div className="form-actions">
          <button type="submit" className="submit-button" disabled={!isFormValid()}>
            {data.submitLabel || 'Submit'}
          </button>
        </div>
      </form>
    </div>
  )
}

export default DepositWidget
