// demowithmcp/frontend/src/components/Chatbot.tsx
import React, { useState, useEffect, useRef } from 'react'
import A2UIRenderer from './A2UIRenderer'
import './Chatbot.css'

interface Message {
  id: number
  type: 'user' | 'bot'
  text: string
  a2ui?: any
  timestamp: Date
}

const AGENT_URL = 'http://localhost:8001'

function Chatbot() {
  const [messages, setMessages] = useState<Message[]>([])
  const [inputText, setInputText] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    // Welcome message
    setMessages([{
      id: 0,
      type: 'bot',
      text: 'Hello! I\'m your banking assistant. I can help you with:\n\n• View account summary\n• Make deposits\n• Process withdrawals\n\nWhat would you like to do?',
      timestamp: new Date()
    }])
  }, [])

  useEffect(() => {
    scrollToBottom()
  }, [messages])

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  const handleSend = async () => {
    if (!inputText.trim() || isLoading) return

    const userMessage: Message = {
      id: Date.now(),
      type: 'user',
      text: inputText.trim(),
      timestamp: new Date()
    }

    setMessages(prev => [...prev, userMessage])
    const prompt = inputText.trim()
    setInputText('')
    setIsLoading(true)

    try {
      const response = await fetch(`${AGENT_URL}/chat`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ message: prompt })
      })

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`)
      }

      const data = await response.json()

      const botMessage: Message = {
        id: Date.now() + 1,
        type: 'bot',
        text: data.text || 'Here is the widget:',
        a2ui: data.a2ui,
        timestamp: new Date()
      }

      setMessages(prev => [...prev, botMessage])
    } catch (error: any) {
      console.error('Error communicating with agent:', error)
      const errorMessage: Message = {
        id: Date.now() + 1,
        type: 'bot',
        text: `Sorry, I encountered an error. ${error.message || 'Please make sure the agent is running on http://localhost:8001'}`,
        timestamp: new Date()
      }
      setMessages(prev => [...prev, errorMessage])
    } finally {
      setIsLoading(false)
    }
  }

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSend()
    }
  }

  return (
    <div className="chatbot">
      <div className="chatbot-messages">
        {messages.map((message) => (
          <div key={message.id} className={`message message-${message.type}`}>
            <div className="message-content">
              {message.type === 'user' ? (
                <div className="message-text">{message.text}</div>
              ) : (
                <>
                  {message.text && (
                    <div className="message-text">{message.text}</div>
                  )}
                  {message.a2ui && (
                    <div className="a2ui-container">
                      <A2UIRenderer message={message.a2ui} />
                    </div>
                  )}
                </>
              )}
            </div>
            <div className="message-time">
              {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
            </div>
          </div>
        ))}
        {isLoading && (
          <div className="message message-bot">
            <div className="message-content">
              <div className="typing-indicator">
                <span></span>
                <span></span>
                <span></span>
              </div>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>
      <div className="chatbot-input">
        <input
          type="text"
          value={inputText}
          onChange={(e) => setInputText(e.target.value)}
          onKeyPress={handleKeyPress}
          placeholder="Ask about your account, make a deposit, or withdrawal..."
          disabled={isLoading}
        />
        <button onClick={handleSend} disabled={isLoading || !inputText.trim()}>
          Send
        </button>
      </div>
    </div>
  )
}

export default Chatbot

// A2UI-Demo/angular-client/src/app/components/chatbot/chatbot.component.ts
import { Component, OnInit, ViewChild, ElementRef, AfterViewChecked } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { A2UIRendererComponent } from '../a2ui-renderer/a2ui-renderer.component';

interface Message {
  id: number;
  type: 'user' | 'bot';
  text?: string;
  a2ui?: any;
  timestamp: Date;
}

@Component({
  selector: 'app-chatbot',
  standalone: true,
  imports: [CommonModule, FormsModule, A2UIRendererComponent],
  templateUrl: './chatbot.component.html',
  styleUrls: ['./chatbot.component.css']
})
export class ChatbotComponent implements OnInit, AfterViewChecked {
  messages: Message[] = [
    {
      id: 1,
      type: 'bot',
      text: 'Hello! I can demonstrate A2UI widgets. Try these commands:\n\n• "show card" or "display card" - Display a card widget\n• "show form" or "display form" - Display a form widget\n• "show table" or "display table" - Display a data table widget\n• "show all" - Display all widgets',
      timestamp: new Date()
    }
  ];
  inputText: string = '';
  isLoading: boolean = false;
  @ViewChild('messagesContainer') private messagesContainer!: ElementRef;

  constructor(private http: HttpClient) {}

  ngOnInit() {
    console.log('Chatbot component initialized');
  }

  ngAfterViewChecked() {
    this.scrollToBottom();
  }

  scrollToBottom(): void {
    try {
      if (this.messagesContainer) {
        this.messagesContainer.nativeElement.scrollTop = 
          this.messagesContainer.nativeElement.scrollHeight;
      }
    } catch (err) {
      console.error('Error scrolling:', err);
    }
  }

  async handleSend() {
    if (!this.inputText.trim() || this.isLoading) return;

    const userMessage: Message = {
      id: Date.now(),
      type: 'user',
      text: this.inputText.trim(),
      timestamp: new Date()
    };

    this.messages.push(userMessage);
    const prompt = this.inputText.trim();
    this.inputText = '';
    this.isLoading = true;

    try {
      // Send prompt to ADK agent
      const response = await this.http.post<any>(
        'http://localhost:8001/chat',
        { message: prompt }
      ).toPromise();

      const botMessage: Message = {
        id: Date.now() + 1,
        type: 'bot',
        text: response.text || 'Here is the widget:',
        a2ui: response.a2ui,
        timestamp: new Date()
      };

      this.messages.push(botMessage);
    } catch (error) {
      console.error('Error communicating with agent:', error);
      const errorMessage: Message = {
        id: Date.now() + 1,
        type: 'bot',
        text: 'Sorry, I encountered an error. Please make sure the ADK agent is running on http://localhost:8001',
        timestamp: new Date()
      };
      this.messages.push(errorMessage);
    } finally {
      this.isLoading = false;
    }
  }

  onKeyPress(event: KeyboardEvent) {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      this.handleSend();
    }
  }
}


<div class="chatbot">
  <div class="chatbot-messages" #messagesContainer>
    <div *ngFor="let message of messages" [class]="'message message-' + message.type">
      <div class="message-content">
        <div *ngIf="message.type === 'user'" class="message-text">{{ message.text }}</div>
        <div *ngIf="message.type === 'bot'">
          <div *ngIf="message.text" class="message-text">{{ message.text }}</div>
          <div *ngIf="message.a2ui" class="a2ui-container">
            <app-a2ui-renderer [message]="message.a2ui"></app-a2ui-renderer>
          </div>
        </div>
      </div>
      <div class="message-time">
        {{ message.timestamp | date:'shortTime' }}
      </div>
    </div>
    <div *ngIf="isLoading" class="message message-bot">
      <div class="message-content">
        <div class="typing-indicator">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
    </div>
  </div>
  <div class="chatbot-input">
    <input
      type="text"
      [(ngModel)]="inputText"
      (keypress)="onKeyPress($event)"
      placeholder="Type a command (e.g., 'show card', 'show form', 'show table', 'show all')..."
      [disabled]="isLoading"
    />
    <button (click)="handleSend()" [disabled]="isLoading || !inputText.trim()">
      Send
    </button>
  </div>
</div>
